default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
switch-white: styles/switch-white.scss
switch-black: styles/switch-black.scss
nintendo-red: styles/nintendo-red.scss
ffxiv: styles/ffxiv.scss